language: node_js
node_js:
  - '15.4.0'

jobs:
  include:
    - script: npm install
    - script: npm run lint
    - script: npm test
    - stage: deploy
      script: npm run release
      deploy:
        provider: releases
        api_key:
          secure: "f009kav6uL9jzifzpEgIBlRgnSZYHIVHYoEOayasEMD1ha31WEj5InHCzBcFt2+0nNqkYKZ7Mx1Mk6aC9xbLgSQd3k+xwJDnXexMuDdl608t5YqyreyEThabVuW9EuwaQ1eHUe/2jTa5Mp5WzyfMKk7gfkLNWvX6cAMvcfF8jil8jy2Yvk7J7g/wRKHh7xofjAXyrFLhDmbXOPSft9nqdD0R/8P3m0fnRKCBQWGAms2Sd5VzZ58U3PJUNE/ApskFADlUzgWEF9Sat78DC2UdgYcvN3vPZE0D3PTD44+6wwegQyNKo2/BQMpP1Un8d94lLe0yG1wMOdTWlItMEbAFw+1S/tMjfBymO5pz2bw5ExA7bVOffzsFF6KZbOe4cxm1laHL8p4FBxoeZ2ZwNiZcfX+uBAuwkHSp/lETbxgbwxsoaXWiDj57a1Zna/5TPdbyYHO9P2X8W4ZecGDvKZoPx+WprGtx7EpxLWbBAYIR03j/UzECJvwCwbGVy004pXLl2S8HuoB3jJvXm7GHjsERYUuKEm5nUaWyj2HPmI7n1K8d4Eqwza8A4qGdo0p5xImywjGE9b8pJ8ntwdWQJN0wgn+Z30hYH9uPWGLe9vRoMf748hDbEYG1rBFMlioiOa9qDz4p/JoLY1gGeVJ9fNlpBMfoxdDgcAMB//tSJxNcAFI="
        file_glob: true
        file: artifacts/*
        skip_cleanup: true
        on:
          repo: globz-eu/recipes
          tags: true
